# This file is part of KLMd project.
#
#  Copyright 2022-2023 by Polar <toddot@protonmail.com>
#
#  Licensed under GNU General Public License 3.0 or later.
#  Some rights reserved. See COPYING, AUTHORS.
#
# @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>


CARGO_OPTIONS=""
RELEASE_TYPE="debug"

target_klmd(){
    info "Build klmd-$RELEASE_TYPE using cargo"
    if [ $RELEASE_TYPE=="debug" ]; then
        exec "cargo build $CARGO_OPTIONS"
    elif [ $RELEASE_TYPE=="release" ]; then
        exec "cargo build --release $CARGO_OPTIONS"
    else
        error "Unknown release type: $RELEASE_TYPE"
    fi
    success "Succesfully built klmd"
}

target_install(){
    target_klmd
    require_root
    info "Cleaning up previous installations..."
    exec rm -f /usr/lib/systemd/system/klmd.service
    exec rm -f /etc/apparmor.d/klmd
    exec rm -f /usr/bin/klmd
    info "Installing klmd..."
    exec cp config/klmd /etc/apparmor.d/klmd
    exec cp config/klmd.service /usr/lib/systemd/system/klmd.service
    exec cp target/$RELEASE_TYPE/klmd /usr/bin/klmd
    exec mkdir -p /var/cache/klm
    success "Succesfully installed klmd"
}
